#!/usr/bin/env python3
"""tests/fuzz-gen.py SEED N DIR [family...] - programs for the differential test (M20, stage F3).

Three families, seeded and reproducible (the same seed gives the same files):
  interval  (a) two De Morgan expressions e1, e2 over i, j, k; the program typechecks iff e1 = e2 in the free De Morgan
            algebra (a generic path applied to both: conversion decides). Ground truth is independent of both checkers:
            the free De Morgan algebra is generated by the four-element lattice DM4, so e1 = e2 iff every valuation into
            DM4 agrees. The file says 'expect: accept' or 'expect: reject'.
  value     (b) a closed Bool (or Nat) built by transporting along random paths in U between Bool and Bool (refl, ua of
            the negation equivalence, sym, compPath, connections), hcomp with random systems, J; well-typed by
            construction, so 'expect: accept' - and the value is then judged three ways (eezott's normal form, Agda,
            the pristine ELF).
  mutant    (c) a corpus program with one token mutated; 'expect: any': whatever eezott says, if it accepts the mutant
            the Agda module must be accepted too.
"""
import os, random, re, sys

def dm4():
    # DM4 = {0, a, b, 1}: a and b incomparable, ~a = a, ~b = b, ~0 = 1 (the four-element De Morgan lattice)
    order = {('0','0'),('0','a'),('0','b'),('0','1'),('a','a'),('a','1'),('b','b'),('b','1'),('1','1')}
    def leq(x, y): return (x, y) in order
    def meet(x, y): return [z for z in '0ab1' if leq(z, x) and leq(z, y) and all(not (leq(w, x) and leq(w, y)) or leq(w, z) for w in '0ab1')][0]
    def join(x, y): return [z for z in '0ab1' if leq(x, z) and leq(y, z) and all(not (leq(x, w) and leq(y, w)) or leq(z, w) for w in '0ab1')][0]
    neg = {'0':'1', '1':'0', 'a':'a', 'b':'b'}
    return meet, join, neg

MEET, JOIN, NEG = dm4()

def ev(e, val):
    k = e[0]
    if k == 'var': return val[e[1]]
    if k == 'i0': return '0'
    if k == 'i1': return '1'
    if k == 'neg': return NEG[ev(e[1], val)]
    if k == 'and': return MEET(ev(e[1], val), ev(e[2], val))
    if k == 'or': return JOIN(ev(e[1], val), ev(e[2], val))

def equal_dm(e1, e2, vars_):
    import itertools
    for vs in itertools.product('0ab1', repeat=len(vars_)):
        val = dict(zip(vars_, vs))
        if ev(e1, val) != ev(e2, val): return False
    return True

def rand_iexpr(rng, vars_, depth):
    if depth == 0 or rng.random() < 0.3:
        r = rng.random()
        if r < 0.8: return ('var', rng.choice(vars_))
        return ('i0',) if r < 0.9 else ('i1',)
    k = rng.choice(['and', 'or', 'neg', 'neg'])
    if k == 'neg': return ('neg', rand_iexpr(rng, vars_, depth - 1))
    return (k, rand_iexpr(rng, vars_, depth - 1), rand_iexpr(rng, vars_, depth - 1))

def show_i(e):
    k = e[0]
    if k == 'var': return e[1]
    if k == 'i0': return 'i0'
    if k == 'i1': return 'i1'
    if k == 'neg': return '(~ %s)' % show_i(e[1])
    return '(%s %s %s)' % (show_i(e[1]), '/\\' if k == 'and' else '\\/', show_i(e[2]))

def gen_interval(rng, n, out):
    vars_ = ['i', 'j', 'k']
    for t in range(n):
        e1 = rand_iexpr(rng, vars_, rng.randint(1, 4)); e2 = rand_iexpr(rng, vars_, rng.randint(1, 4))
        if rng.random() < 0.5:   # half the time a pair known equal by a De Morgan law, rewritten
            e2 = rewrite(rng, e1)
        eq = equal_dm(e1, e2, vars_)
        s1, s2 = show_i(e1), show_i(e2)
        # the intervals bound outside (a Pi over I is a pretype: no Path over it); a constant path between p e1 and p e2
        # checks iff its endpoints are convertible, i.e. iff e1 = e2 as interval expressions
        prog = ("-- interval pair %d: %s  vs  %s; equal in the free De Morgan algebra (DM4 valuations): %s\n"
                "-- expect: %s\n"
                "def t (A : U) (x y : A) (p : Path A x y) (i j k : I) : Path A (p %s) (p %s) := \\_ -> p %s\n"
                "def main : Bool := true\n") % (t, s1, s2, eq, 'accept' if eq else 'reject', s1, s2, s1)
        open(os.path.join(out, 'gen_interval_%03d.tt' % t), 'w').write(prog)

def rewrite(rng, e):
    """a De Morgan-law rewrite of e (equal by construction), applied at a random position"""
    k = e[0]
    laws = []
    if k == 'neg' and e[1][0] == 'neg': laws.append(e[1][1])
    if k == 'neg' and e[1][0] == 'and': laws.append(('or', ('neg', e[1][1]), ('neg', e[1][2])))
    if k == 'neg' and e[1][0] == 'or': laws.append(('and', ('neg', e[1][1]), ('neg', e[1][2])))
    if k in ('and', 'or'): laws.append((k, e[2], e[1]))
    if k == 'and': laws.append(('and', e[1], ('or', e[1], e[2])) if rng.random() < 0.5 else ('and', ('or', e[1], e[2]), e[1]))  # absorption: x /\ (x \/ y) = x, applied to (e1 /\ e2)? no: x /\ (x \/ y) = x, so replace e by (e /\ (e \/ z))
    if k == 'or': laws.append(('or', e, ('and', e, ('var', rng.choice('ijk')))))   # x \/ (x /\ z) = x
    if not laws or rng.random() < 0.4:
        if k in ('and', 'or'): return (k, rewrite(rng, e[1]), e[2]) if rng.random() < 0.5 else (k, e[1], rewrite(rng, e[2]))
        if k == 'neg': return ('neg', rewrite(rng, e[1]))
        return e
    return rng.choice(laws)

# ---- (b) values: paths in U between Bool and Bool, transports, hcomps, J
def gen_value(rng, n, out):
    for t in range(n):
        lines = ["-- value %d: transports along random paths Bool = Bool, compositions and connections; judged three ways" % t,
                 "-- expect: accept",
                 "def notnot (b : Bool) : Path Bool (not (not b)) b := elim Bool (\\b -> Path Bool (not (not b)) b) (\\_ -> true) (\\_ -> false) b",
                 "def notEquiv : Equiv Bool Bool := isoToEquiv Bool Bool not not notnot notnot",
                 "def N : Path U Bool Bool := ua Bool Bool notEquiv",
                 "def R : Path U Bool Bool := \\_ -> Bool"]
        helpers = []
        def named(body):   # every path construct is a definition: applications are then to names (a bare lambda applied cannot be inferred)
            nm = 'p%d' % len(helpers); helpers.append('def %s : Path U Bool Bool := %s' % (nm, body)); return nm
        def rand_path(depth):
            if depth == 0 or rng.random() < 0.25: return rng.choice(['N', 'R'])
            r = rng.random()
            if r < 0.3: return named('sym U Bool Bool %s' % rand_path(depth - 1))
            if r < 0.7: return named('compPath U Bool Bool Bool %s %s' % (rand_path(depth - 1), rand_path(depth - 1)))
            if r < 0.85: return named('\\i -> %s (i /\\ i)' % rand_path(depth - 1))
            return named('\\i -> %s (~ (~ i))' % rand_path(depth - 1))
        def rand_bool(depth):
            if depth == 0 or rng.random() < 0.3: return rng.choice(['true', 'false'])
            r = rng.random()
            if r < 0.45: return '(transport Bool Bool %s %s)' % (rand_path(depth - 1), rand_bool(depth - 1))
            if r < 0.6: return '(not %s)' % rand_bool(depth - 1)
            if r < 0.75:   # hcomp with an empty system: the value is the base
                return '(hcomp Bool i0 (\\j -> []) %s)' % rand_bool(depth - 1)
            if r < 0.9:    # the transport filler: a path over P from b to its transport (transp along P restricted to i /\ k)
                P, b = rand_path(depth - 1), rand_bool(depth - 1)
                nm = 'sq%d' % len(helpers)
                helpers.append('def %s : PathP (\\i -> %s i) %s (transport Bool Bool %s %s) := \\i -> transp (\\k -> %s (i /\\ k)) i0 %s' % (nm, P, b, P, b, P, b))
                return '(%s %s)' % (nm, rng.choice(['i0', 'i1']))
            return '(and %s %s)' % (rand_bool(depth - 1), rand_bool(depth - 1))
        body = rand_bool(rng.randint(2, 5))
        lines.extend(helpers)
        lines.append("def main : Bool := %s" % body)
        open(os.path.join(out, 'gen_value_%03d.tt' % t), 'w').write('\n'.join(lines) + '\n')

# ---- (c) mutants of corpus programs
TOKEN = re.compile(r"[A-Za-z_][A-Za-z0-9_']*|i0|i1|~|/\\|\\/|->|:=|[()\[\]|,:\\]")
SWAPS = {'i0': 'i1', 'i1': 'i0', '/\\': '\\/', '\\/': '/\\', 'true': 'false', 'false': 'true', 'zero': 'one', 'fst': 'snd', 'snd': 'fst', '~': ''}
def gen_mutant(rng, n, out, corpus):
    files = sorted(f for f in os.listdir(corpus) if f.endswith('.tt'))
    for t in range(n):
        f = rng.choice(files); src = open(os.path.join(corpus, f)).read()
        toks = [(m.start(), m.end(), m.group()) for m in TOKEN.finditer(src) if not src[:m.start()].split('\n')[-1].lstrip().startswith('--')]
        cands = [(a, b, s) for a, b, s in toks if s in SWAPS]
        if not cands: continue
        a, b, s = rng.choice(cands)
        mut = src[:a] + SWAPS[s] + src[b:]
        open(os.path.join(out, 'gen_mutant_%03d.tt' % t), 'w').write("-- mutant %d of %s: '%s' -> '%s' at offset %d\n-- expect: any\n" % (t, f, s, SWAPS[s], a) + mut)

def main():
    seed, n, out = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3]
    fams = sys.argv[4:] or ['interval', 'value', 'mutant']
    os.makedirs(out, exist_ok=True)
    rng = random.Random(seed)
    corpus = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tt')
    if 'interval' in fams: gen_interval(rng, n, out)
    if 'value' in fams: gen_value(rng, n, out)
    if 'mutant' in fams: gen_mutant(rng, n, out, corpus)

if __name__ == '__main__': main()
